# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='decs',
        ),
    ]
