# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 01:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0002_remove_post_decs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decs',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
    ]
